- name: Configure MOTD on Cisco IOS
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Set MOTD
      cisco.ios.ios_banner:
        banner: motd     
        text: "{{ motd_message }}"
        state: present        
